# Generated by Django 4.1.4 on 2022-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_food', '0002_alter_category_date_added_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000000),
        ),
    ]
