# Generated by Django 4.1.4 on 2022-12-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_food', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
