# Generated by Django 4.1.4 on 2022-12-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopper',
        ),
    ]
